# Generated by Django 5.2.17 on 2026-08-31 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrustReport',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trust_report', serialize=False, to='products.product')),
                ('total_reviews', models.IntegerField()),
                ('fake_count', models.IntegerField()),
                ('authenticity_rate', models.FloatField(help_text='% de reviews jugées normales')),
                ('raw_avg_rating', models.FloatField(help_text='Moyenne brute, toutes reviews confondues')),
                ('adjusted_rating', models.FloatField(help_text='Moyenne calculée uniquement sur les reviews de confiance')),
                ('summary_text', models.TextField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('verdict', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='reviews.review')),
                ('near_dup_score', models.FloatField()),
                ('is_burst_day', models.BooleanField()),
                ('is_unverified', models.BooleanField()),
                ('rating_deviation', models.FloatField()),
                ('exclamation_count', models.FloatField()),
                ('word_count', models.FloatField()),
                ('avg_word_len', models.FloatField()),
                ('positive_superlative_count', models.FloatField()),
                ('negative_superlative_count', models.FloatField()),
                ('iso_prediction', models.SmallIntegerField(help_text='-1 = anomalie suspecte, 1 = normale')),
                ('iso_anomaly_score', models.FloatField(help_text='Plus bas = plus suspect')),
                ('anomaly_frequency', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
