# Generated by Django 5.2.17 on 2026-08-31 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('review_title', models.CharField(blank=True, max_length=255)),
                ('review_url', models.URLField(blank=True)),
                ('review_position', models.IntegerField(blank=True, null=True)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('helpful_vote_count', models.IntegerField(default=0)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('content_clean', models.TextField()),
                ('text_length', models.IntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Date de la review sur Amazon', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout dans notre DB")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['product', 'posted_at'], name='reviews_rev_product_6190c6_idx')],
            },
        ),
    ]
